name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v

  build-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: swift build -c release -v

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          xcodebuild build-for-testing \
            -scheme CombineViewModel-Package \
            -destination 'platform=iOS Simulator,name=iPhone 11'
      - name: Run tests
        run: |
          xcodebuild test-without-building \
            -scheme CombineViewModel-Package \
            -destination 'platform=iOS Simulator,name=iPhone 11'

  build-release-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Bindings
        run: |
          xcodebuild -configuration Release \
            -scheme Bindings \
            -destination 'platform=iOS Simulator,name=iPhone 11'
      - name: Build UIKitBindings
        run: |
          xcodebuild -configuration Release \
            -scheme UIKitBindings \
            -destination 'platform=iOS Simulator,name=iPhone 11'
      - name: Build CombineViewModel
        run: |
          xcodebuild -configuration Release \
            -scheme CombineViewModel \
            -destination 'platform=iOS Simulator,name=iPhone 11'
